### PR TITLE
Make OpenStack driver compatible with last version Essex

### PR DESCRIPTION
**Pull request by grozeille**
Be able to choose the Authentication mode, to be able to use the driver with Essex version of OpenStack, or older.
Reduce the amount of needed settings: some information are take from the REST WebService.

### CODE REVIEW

**Comment by gkorland** [comment]
Do you have a running env' we can use for testing the new driver?

**Comment by grozeille** [comment]
I tested it on http://www.enocloud.com/
I sent the screenshots to Yaron, who asked me to do this pull request.
But I didn't test it on older version of OpenStack: it should work because you can choose the Authentication mode, but more test will be better.

**Comment by grozeille** [comment]
Hi,

Until you includes my changes, I did a fork: https://github.com/fastconnect/cloudify-openstack-driver
It would be nice to split the drivers in different github repositories. You can include them as git modules then.
It's too bad to have to fork all the cloudify project just to enhance an existing driver :)

**Comment by gkorland** [comment]
We're going to support it based on JClouds 1.5.2.

**Comment by noelking** [comment]
Hi 

Will OpenStack Folsom release also be supported along with Essex?

Thanks

Noel

**Comment by gkorland** [comment]
Probably, but we'll have to check it.

**Comment by noelking** [comment]
Thanks for the prompt reply.

Regards,
Noel

**Pull request closed without merging**
