### PR TITLE
Detection of wget and curl

### PR DESCRIPTION
**Pull request by paolostivanin**
Now the bootstrap script will check for wget and curl so if one is not present the other can be used!

### CODE REVIEW

**Comment by barakm** [comment]
Hi, 
We need you to sign the Contributor License Agreement before we can accept a contribution.
Please have a look here:
http://www.cloudifysource.org/guide/2.6/contribute/how_to

**Comment by paolostivanin** [comment]
- JIRA account created;
- signed & sent the CLA;
  :-)

**Comment by ghost** [comment]
Hi man, could you please share SLAE32 course if you have ?

**Comment by paolostivanin** [comment]
@electric-mind this is not the place for personal request.
However:
1) i will start the course on mid of october and
2) in respect of Vivek i will not share the course material.

**Pull request merged**
