### PR TITLE
Serviceutils

### PR DESCRIPTION
**Pull request by nukemberg**
added a few handy methods to service utils, cause many programs listen on primary interface and not on localhost.

### CODE REVIEW

**Comment by barakm** [comment]
Using the primary interface can have  unforseen results on some clouds. Using localhost is not perfect, but it is consistent, and works for the vast majority of services.

The key file fix will be merged into the code.

**Comment by nukemberg** [comment]
Can you at least merge the functions that allow retrieval of the primary
interface and querying host, port in addition? That way we can support
consistency while supporting services that bind to primary interface?
On May 24, 2012 2:09 PM, "barakm" <
reply@reply.github.com>
wrote:

**Comment by barakm** [comment]
Ok, I will add those to the merge

**Comment by nukemberg** [comment]
10x

**Comment by gkorland** [comment]
Merged manually

**Pull request closed without merging**
